package cn.com.flaginfo.platform.terminal.mysql.entity;

import java.util.Date;

public class CoreUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.mail
     *
     * @mbggenerated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.flag
     *
     * @mbggenerated
     */
    private Boolean flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.depart_id
     *
     * @mbggenerated
     */
    private String departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.detail_type
     *
     * @mbggenerated
     */
    private String detailType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_core_user.amount
     *
     * @mbggenerated
     */
    private Integer amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.id
     *
     * @return the value of t_core_user.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.id
     *
     * @param id the value for t_core_user.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.account
     *
     * @return the value of t_core_user.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.account
     *
     * @param account the value for t_core_user.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.real_name
     *
     * @return the value of t_core_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.real_name
     *
     * @param realName the value for t_core_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.pwd
     *
     * @return the value of t_core_user.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.pwd
     *
     * @param pwd the value for t_core_user.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.mail
     *
     * @return the value of t_core_user.mail
     *
     * @mbggenerated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.mail
     *
     * @param mail the value for t_core_user.mail
     *
     * @mbggenerated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.flag
     *
     * @return the value of t_core_user.flag
     *
     * @mbggenerated
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.flag
     *
     * @param flag the value for t_core_user.flag
     *
     * @mbggenerated
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.updater
     *
     * @return the value of t_core_user.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.updater
     *
     * @param updater the value for t_core_user.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.update_time
     *
     * @return the value of t_core_user.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.update_time
     *
     * @param updateTime the value for t_core_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.type
     *
     * @return the value of t_core_user.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.type
     *
     * @param type the value for t_core_user.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.depart_id
     *
     * @return the value of t_core_user.depart_id
     *
     * @mbggenerated
     */
    public String getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.depart_id
     *
     * @param departId the value for t_core_user.depart_id
     *
     * @mbggenerated
     */
    public void setDepartId(String departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.detail_type
     *
     * @return the value of t_core_user.detail_type
     *
     * @mbggenerated
     */
    public String getDetailType() {
        return detailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.detail_type
     *
     * @param detailType the value for t_core_user.detail_type
     *
     * @mbggenerated
     */
    public void setDetailType(String detailType) {
        this.detailType = detailType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_core_user.amount
     *
     * @return the value of t_core_user.amount
     *
     * @mbggenerated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_core_user.amount
     *
     * @param amount the value for t_core_user.amount
     *
     * @mbggenerated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }
}