package cn.com.flaginfo.platform.terminal.mysql.mapper;

import cn.com.flaginfo.platform.terminal.mysql.entity.CoreUser;
import cn.com.flaginfo.platform.terminal.mysql.entity.CoreUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CoreUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_user
     *
     * @mbggenerated
     */
    int countByExample(CoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_user
     *
     * @mbggenerated
     */
    int deleteByExample(CoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_user
     *
     * @mbggenerated
     */
    int insert(CoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_user
     *
     * @mbggenerated
     */
    int insertSelective(CoreUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_user
     *
     * @mbggenerated
     */
    List<CoreUser> selectByExampleWithRowbounds(CoreUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_user
     *
     * @mbggenerated
     */
    List<CoreUser> selectByExample(CoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoreUser record, @Param("example") CoreUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_core_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoreUser record, @Param("example") CoreUserExample example);
}